### ISSUE TITLE
Versão 1.4.0 - Odoo V14 - Erro ao adicionar Certificado A1 -  from_buffer() cannot return the address of a unicode object

### ISSUE THREAD

**Issue by renanteixeira** [erpbrasil/erpbrasil.assinatura#34]
Olá,

Ao tentar adicionar um novo certificado no Odoo Versão 14.0 com a **versão 1.4.0** dessa lib, é apresentado o erro abaixo.

odoo.api: call l10n_br_fiscal.certificate().create({'active': True, 'type': 'nf-e', 'subtype': 'a1', 'file': 'MIIkc....'
..., 'password': 'Cert2022#', 'date_start': False, 'date_expiration': False, 'message_follower_ids': [], 'activity_ids': [], 'message_ids': []})

**WARNING db_1205 odoo.http: Cannot load Certificate !** 
 **from_buffer() cannot return the address of a unicode object** 
![image](https://user-images.githubusercontent.com/6026211/168636609-02dd8b5a-a1bc-4954-bfe8-a9a73618c041.png)

Com a versão 1.2.0, o certificado é adicionado normalmente, apenas com o Warning abaixo

db_1205 py.warnings: /home/Dev/Odoo/v14/pyenv/1205-env/lib/python3.8/site-packages/erpbrasil/assinatura/certificado.py:29: DeprecationWarning: str for passphrase is no longer accepted, use bytes
  self._pkcs12 = crypto.load_pkcs12(self._arquivo,
![image](https://user-images.githubusercontent.com/6026211/168637489-8a77c371-09b7-4dbb-a529-e642c410ed29.png)

**Comment by netosjb** [comment]
O erro na verdade está repositório da localização, sugeri uma PR com a correção: https://github.com/OCA/l10n-brazil/pull/1981
