### ISSUE TITLE
Incompatibilidade com versões mais recentes do signxml.

### ISSUE THREAD

**Issue by antoniospneto** [erpbrasil/erpbrasil.assinatura#38]
É preciso testar se a biblioteca está compatível com as versões mais recentes do **signxml** (versão acima do 2.9.0)
Algumas pessoas no telegram reportaram ter problema e tiveram que fazer downgrade pro 2.9.0.

**Comment by leogregianin** [comment]
Dá uma olhada nessa alteração: https://github.com/TadaSoftware/PyNFe/pull/227, o método da assinatura é a mesma.

**Comment by antoniospneto** [comment]
resolve com o https://github.com/erpbrasil/erpbrasil.assinatura/pull/39
